---
- name: Add InfluxDB Key on Debian.
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present
  when: ansible_distribution == "Debian"

- name: Add InfluxDB Repository on Debian.
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable"
    state: present
  when: ansible_distribution == "Debian"

- name: install > Packages
  apt:
    name: "{{ manala_influxdb_install_packages|default(manala_influxdb_install_packages_default, True) }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
