---
- name: Add InfluxDB Repository on Debian.
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution }} {{ ansible_distribution_codename }} stable"

- name: install > Packages
  apt:
    name: "{{ manala_influxdb_install_packages|default(manala_influxdb_install_packages_default, True) }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
